# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpregi', '0002_auto_20170914_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rplist',
            name='VisualfieldLt',
        ),
        migrations.RemoveField(
            model_name='rplist',
            name='VisualfieldRt',
        ),
    ]
